HOST: http://hackerclub.jit.su/

--- Hacker Club API v1 ---

--
Usage Resources
The following is a section of resources related to the usage of our visualization at http//hackerclub.jit.su/force.html
--
List events from the visualization
GET /force
< 200
< Content-Type: application/json
{ "source": "njitsu", "coordX":0, "coordY":0 }
